-- 1. Criar a tabela
CREATE TABLE ITENS_NF (
    ID_NF INT,
    ID_ITEM INT,
    COD_PROD INT,
    VALOR_UNIT DECIMAL(10,2),
    QUANTIDADE INT,
    DESCONTO DECIMAL(5,2)
);

-- a) Itens vendidos sem desconto
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT
FROM ITENS_NF
WHERE DESCONTO IS NULL OR DESCONTO = 0;

-- b) Itens vendidos com desconto
SELECT 
ID_NF,
ID_ITEM,
COD_PROD,
VALOR_UNIT,
VALOR_UNIT - (VALOR_UNIT * (DESCONTO/100)) AS VALOR_VENDIDO
FROM ITENS_NF
WHERE DESCONTO > 0;

-- c) Alterar desconto nulo para 0
UPDATE ITENS_NF
SET DESCONTO = 0
WHERE DESCONTO IS NULL;

-- d) Itens vendidos com valor total e valor vendido
SELECT
ID_NF,
ID_ITEM,
COD_PROD,
VALOR_UNIT,
QUANTIDADE * VALOR_UNIT AS VALOR_TOTAL,
DESCONTO,
VALOR_UNIT - (VALOR_UNIT * (DESCONTO/100)) AS VALOR_VENDIDO
FROM ITENS_NF;

-- e) Valor total das Notas Fiscais
SELECT
ID_NF,
SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL
FROM ITENS_NF
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

-- f) Valor vendido das Notas Fiscais
SELECT
ID_NF,
SUM(VALOR_UNIT - (VALOR_UNIT * (DESCONTO/100))) AS VALOR_VENDIDO
FROM ITENS_NF
GROUP BY ID_NF
ORDER BY VALOR_VENDIDO DESC;

-- g) Produto que mais vendeu
SELECT
COD_PROD,
SUM(QUANTIDADE) AS QUANTIDADE
FROM ITENS_NF
GROUP BY COD_PROD
ORDER BY QUANTIDADE DESC;

-- h) NF com mais de 10 unidades vendidas de um produto
SELECT
ID_NF,
COD_PROD,
SUM(QUANTIDADE) AS QUANTIDADE
FROM ITENS_NF
GROUP BY ID_NF, COD_PROD
HAVING SUM(QUANTIDADE) > 10;

-- i) Valor total das NF maior que 500
SELECT
ID_NF,
SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOT
FROM ITENS_NF
GROUP BY ID_NF
HAVING SUM(QUANTIDADE * VALOR_UNIT) > 500
ORDER BY VALOR_TOT DESC;

-- j) Média de desconto por produto
SELECT
COD_PROD,
AVG(DESCONTO) AS MEDIA
FROM ITENS_NF
GROUP BY COD_PROD;

-- k) Menor, maior e média de desconto por produto
SELECT
COD_PROD,
MIN(DESCONTO) AS MENOR,
MAX(DESCONTO) AS MAIOR,
AVG(DESCONTO) AS MEDIA
FROM ITENS_NF
GROUP BY COD_PROD;

-- l) NF com mais de 3 itens vendidos
SELECT
ID_NF,
COUNT(ID_ITEM) AS QTD_ITENS
FROM ITENS_NF
GROUP BY ID_NF
HAVING COUNT(ID_ITEM) > 3;

-- 2. Criar banco Universidade
CREATE DATABASE Universidade;

-- Tabela Alunos
CREATE TABLE Alunos(
MAT INT PRIMARY KEY,
nome VARCHAR(100),
endereco VARCHAR(100),
cidade VARCHAR(50)
);

-- Tabela Disciplinas
CREATE TABLE Disciplinas(
COD_DISC INT PRIMARY KEY,
nome_disc VARCHAR(100),
carga_hor INT
);

-- Tabela Professores
CREATE TABLE Professores(
COD_PROF INT PRIMARY KEY,
nome VARCHAR(100),
endereco VARCHAR(100),
cidade VARCHAR(50)
);

-- Tabela Turma
CREATE TABLE Turma(
COD_DISC INT,
COD_TURMA INT,
COD_PROF INT,
ANO INT,
horario VARCHAR(20),

FOREIGN KEY (COD_DISC) REFERENCES Disciplinas(COD_DISC),
FOREIGN KEY (COD_PROF) REFERENCES Professores(COD_PROF)
);

-- Tabela Histórico
CREATE TABLE Historico(
MAT INT,
COD_DISC INT,
COD_TURMA INT,
COD_PROF INT,
ANO INT,
frequencia DECIMAL(5,2),
nota DECIMAL(5,2),

FOREIGN KEY (MAT) REFERENCES Alunos(MAT)
);

-- Inserir alunos
INSERT INTO Alunos VALUES
(2015010101, 'JOSE DE ALENCAR', 'RUA DAS ALMAS', 'NATAL'),
(2015010102, 'JOÃO JOSÉ', 'AVENIDA RUY CARNEIRO', 'JOÃO PESSOA'),
(2015010103, 'MARIA JOAQUINA', 'RUA CARROSSEL', 'RECIFE');